baseURL = 'https://tgib23.github.io/'
languageCode = 'en-us'
title = 'some tech and other talks'
googleAnalytics = "UA-8617707-5"

[permalinks]
  post = "/blog/:year/:month/:day/:slug"

[params]
    amazonJpAffiliate = "bigt23-22"
    amazonUsAffiliate = "yamadasatoshi-20"
    customCSS = ["/css/custom.css"]
    subtitle = "ruby, rails, book reviews"
