baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[permalinks]
  post = "/blog/:year/:month/:day/:slug"

[params]
    amazonJpAffiliate = "bigt23-22"
    customCSS = ["/css/custom.css"]

